### ISSUE TITLE
[Feature Request] Margin & Horizontal Reading

### ISSUE THREAD

**Issue by EternalBot** [LNReader/lnreader#428]
May I ask if it is possible to add following this features?@

- **Margin Control** : I kinda feel uncomfortable when reading specifically **Top & Bottom margin**. 
My humble request plz kindly do something about top & bottom margin ur next update & also if possible do too ~~left & right margin~~

- **Horizontal Readng**: I kinda like Horizontal Reading but that's my optional request. If is it possible too?

**Comment by SkillGG** [comment]
If you use HTML viewer
You can add css ```css
chapter {
    padding: <top> <right> <bottom> <left>;
    /* for padding to work (display is originally inline which doesn't show left/right padding */
    display: block;
}```
Where `<top>`, `<right>`, `<bottom>` and `<left>` are sizes of the margins you want to have for example
```css
chapter {
     padding: 10px 25px 10px 25px;
    /* for padding to work (display is originally inline which doesn't show left/right padding */
    display: block;
}
```

**Comment by EternalBot** [comment]
Top & bottom not working

**Comment by rajarsheechatterjee** [comment]
> Top & bottom not working

Padding would only be there at the top and bottom of chapter, it'll be not there as you scroll.

**Comment by SkillGG** [comment]
If you really want top and bottom margins all the time you can do 
```css
chapter {
 padding: 10px 25px 10px 25px;
 position: fixed;
 height: 75vh;
 overflow-y:scroll;
 display:block;
}
```
_**__This will make chapter not know where / if you finished reading the chapter__**_

**Comment by SkillGG** [comment]
You can simulate top margin like that:
```css
chapter::before {
    content:"";
    height: 100px;
    display: block;
    top:0;
    width:100vw;
    position: fixed;
    background-color: #292832;
}
chapter {
    padding-top: 100px;
    display: block;
}
```
